### ISSUE TITLE
Publish for sbt 1.0.0

### ISSUE THREAD

**Issue by magicknot** [codacy/sbt-codacy-coverage#44]
### Scala Version (2.10.x / etc)
2.12.0

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Open `project/build.properties` and set `sbt.version=1.0.0`
2. Run sbt 
3. No errors found

### Actual Behavior

1. Open `project/build.properties` and set `sbt.version=1.0.0`
2. Run sbt 
3. 

```scala
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.codacy#sbt-codacy-coverage;1.3.8: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.codacy:sbt-codacy-coverage:1.3.8 (scalaVersion=2.12, sbtVersion=1.0)
```

**Comment by pedrorijo91** [comment]
Hey @magicknot 

Thanks for reporting the problem. Would you be interested in contributing through a PR?

Besides updating the sbt version it will be needed to update other dependencies probably:

- sbt-sonatype
- sbt-pgp
- sbt-updates
- codacy-api-scala
- coverage-parser

not sure if the first 3 already have support for sbt 1.0.0. The last 2 are Codacy projects, so PRs are welcome! Otherwise we will try to release a sbt 1.0.0 version as soon as possible :)

> maybe useful: http://www.scala-sbt.org/1.0/docs/sbt-1.0-Release-Notes.html

**Comment by darkfrog26** [comment]
* [X] sbt-sonatype
* [X] sbt-pgp
* [X] sbt-updates
* [X] codacy-api-scala (not an SBT plugin)
* [X] coverage-parser (not an SBT plugin)

It looks like there are no dependencies holding you back from releasing this for SBT 1.0.
